### ISSUE TITLE
To add relevant data at testimonials section[BUG]

### ISSUE THREAD

**Issue by Kirankp25** [Susmita-Dey/Moody#13]
**Describe the bug**
data at testimonials seem to be duplicated and not relevant

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot (309)](https://user-images.githubusercontent.com/87818185/193441568-8d30343c-6a36-434e-a398-2fedb08454fc.png)

**Additional context**
I would like to resolve this issue pls assign me

**Comment by Susmita-Dey** [comment]
@Kirankp25 You have made a spam issue. It's for the website repo called `Moody-website`. This is the extension repo.
