### ISSUE TITLE
[FEATURE] add website link in about section 

### ISSUE THREAD

**Issue by Niravprajapati1** [Susmita-Dey/Moody#14]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 
Finding website link is hard for me 
**Describe the solution you'd like**
I wanna see the website but for that i opened environments section then clicked on view development 
**Describe alternatives you've considered**
Add website link in about section or maybe in readme
**Additional context**

**Comment by rakshitgondwal** [comment]
Hey!! This is 100% an issue that needs to be resolved imo. I made the same change when I contributed to Sukoon project.
I would like to solve this one too.

**Comment by Susmita-Dey** [comment]
@Niravprajapati1 Add it to the `README.md` file
