### ISSUE TITLE
[FEATURE]  Loading animation when fetching data from api its look cool

### ISSUE THREAD

**Issue by Shyam3050** [Susmita-Dey/Moody#19]
when we fetch jokes from dad joke api loading animation will be added.
for fetching recipe API also
 Search button for search bar
 

![lOADING](https://user-images.githubusercontent.com/91086813/194001988-52ec8a9c-8c76-4948-85f3-e0ba487563a6.jpg)

**Comment by Chaitanya-087** [comment]
i would like to work on this
