### ISSUE TITLE
[BUG] Hover Effect missing and loading twitter button Every time when fetch happen

### ISSUE THREAD

**Issue by Shyam3050** [Susmita-Dey/Moody#20]
Hover Effect not working for Space, cooking, and music buttons.
We need to fix the Twitter link button Every time loads when fetching new jokes etc.
![Screenshot (29)](https://user-images.githubusercontent.com/91086813/194003037-201b8bbc-93ad-421b-8853-9b80b821e89f.png)
![Screenshot (28)](https://user-images.githubusercontent.com/91086813/194003068-5fa1a524-b89f-4419-9b0a-097049d40166.png)
![Screenshot (32)](https://user-images.githubusercontent.com/91086813/194003145-c26152f2-7143-4ce7-b3e3-43b46669b903.png)

**Comment by AadeshKabra** [comment]
Can I work on this?

**Comment by Shyam3050** [comment]
i am working on this you can create new issue
