### ISSUE TITLE
Loading animation for  cooking page and Search button for search bar

### ISSUE THREAD

**Issue by Shyam3050** [Susmita-Dey/Moody#26]
![Screenshot (30)](https://user-images.githubusercontent.com/91086813/194699030-70c420e2-6242-4b32-be55-9acb96a50a0e.png)

After

![Screenshot (30)](https://user-images.githubusercontent.com/91086813/194699149-00059383-9ad4-497b-bc21-c14043b8455c.png)

**Comment by Shyam3050** [comment]
Assign me for doing this 
Search bar and Loading animation

**Comment by ElectricPlant19** [comment]
assign me please i can work on it
