### ISSUE TITLE
[chore]: create SVG icons for the other emotions

### ISSUE THREAD

**Issue by akebu6** [Susmita-Dey/Moody#4]
Kindly create the SVG icons for the other emotions so it is easy to reference them in the code. The following SVG icons are needed:
- fear
- anxiety
- hate

**Comment by Susmita-Dey** [comment]
> Kindly create the SVG icons for the other emotions so it is easy to reference them in the code. The following SVG icons are needed:
> 
> * fear
> * anxiety
> * hate

Okay, I'm doing it.

**Comment by Susmita-Dey** [comment]
@akebu6 Emojis are added.

**Comment by akebu6** [comment]
All right, thanks 👍
