### ISSUE TITLE
Missing the Issue Templates

### ISSUE THREAD

**Issue by FahimFBA** [Susmita-Dey/Moody#6]
The project is currently missing the issue templates which would help others submit their issue in a categorized way. If you are interested in adding them, then I can submit a pull request with some relevant issue templates.

**Comment by Susmita-Dey** [comment]
> The project is currently missing the issue templates which would help others submit their issue in a categorized way. If you are interested in adding them, then I can submit a pull request with some relevant issue templates.

Do you want to work on this issue?

**Comment by FahimFBA** [comment]
Yeah, sure!

**Comment by Susmita-Dey** [comment]
@FahimFBA Go ahead
